name: build

on: push

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: restore dependencies
      run: dotnet restore
      
    - name: build
      run: dotnet publish "src/Elden Ring Debug Tool WPF/Elden-Ring-Debug-Tool-WPF.csproj" /p:PublishProfile=FolderProfile.pubxml

  - name:
      uses: edgarrc/action-7z@v1
      with:
      args: 7za.exe a -t7z "Elden Ring Debug Tool.7z" .\bin\Publish\win-x64\* -xr!*.pdb


    
