name: build

on: push

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: restore dependencies
      run: dotnet restore
      
    - name: build
      run: dotnet publish "src/Elden-Ring-Debug-Tool-WPF/Elden-Ring-Debug-Tool-WPF.csproj" --configuration Publish /p:PublishProfile=FolderProfile.pubxml

    - run: 7z a -t7z "Elden Ring Debug Tool.7z" "src/Elden-Ring-Debug-Tool-WPF/bin/Publish/win-x64/*"
    # - uses: grez72/action-zip-7z@v0.1.0
    #   with:
    #     args: 7z a -t7z 'Elden Ring Debug Tool.7z' src/Elden-Ring-Debug-Tool-WPF/bin/Publish/win-x64/* -xr!*.pdb

    - name: get-net-sdk-project-versions-action
      uses: kzrnm/get-net-sdk-project-versions-action@v1.1.1
      id: get-version
      with:
        proj-path: src/Elden-Ring-Debug-Tool-WPF/Elden-Ring-Debug-Tool-WPF.csproj


    - run: move 'Elden Ring Debug Tool.7z' './src/Elden-Ring-Debug-Tool-WPF/bin/Publish/Elden Ring Debug Tool ${{steps.get-version.outputs.version}}.7z'
    

    - name: publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: src/Elden-Ring-Debug-Tool-WPF/bin/Publish/*.7zip

    
