name: build

on: push

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: restore dependencies
      run: dotnet restore
      
    - name: build
      run: dotnet publish "src/Elden Ring Debug Tool WPF/Elden-Ring-Debug-Tool-WPF.csproj" /p:PublishProfile=FolderProfile.pubxml

    - name: Action 7z
      uses: edgarrc/action-7z@v1
        args: 7z a -t7z -mx=9 build.7z ./build/

    - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: src/Elden Ring Debug Tool/bin/Publish/*.7zip

    
